=== shenmareparas/Internet-and-Web-Programming/xml files/cookie.dtd
<!ELEMENT food (cookie+)>

<!ELEMENT cookie (calories, carbs, protein, fat, sugar)>
<!ATTLIST cookie type CDATA #REQUIRED>

<!ELEMENT calories (#PCDATA)>
<!ELEMENT carbs (#PCDATA)>
<!ELEMENT protein (#PCDATA)>

<!ELEMENT fat (monounsatfat, polyunsatfat, saturatedfat, cholesterol)>
<!ELEMENT monounsatfat (#PCDATA)>
<!ELEMENT polyunsatfat (#PCDATA)>
<!ELEMENT saturatedfat (#PCDATA)>
<!ELEMENT cholesterol (#PCDATA)>


<!ELEMENT sugar (#PCDATA)>

=== shenmareparas/Internet-and-Web-Programming/xml files/cookie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE food SYSTEM "cookie.dtd">

<food>
    <cookie type = "almond">
        <calories>123</calories>
        <carbs>123</carbs>
        <protein>123</protein>
        <fat>
            <monounsatfat>123</monounsatfat>
            <polyunsatfat>123</polyunsatfat>
            <saturatedfat>123</saturatedfat>
            <cholesterol>123</cholesterol>
        </fat>
        <sugar>123</sugar>
    </cookie>
    <cookie type = "cashew">
        <calories>123</calories>
        <carbs>123</carbs>
        <protein>123</protein>
        <fat>
            <monounsatfat>123</monounsatfat>
            <polyunsatfat>123</polyunsatfat>
            <saturatedfat>123</saturatedfat>
            <cholesterol>123</cholesterol>
        </fat>
        <sugar>123</sugar>
    </cookie>
</food>
